#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
OUTPUT=${1:-"$ROOT/supabase/functions/legal/pages.ts"}

{
    echo "// Generated by scripts/generate_legal_pages.sh."
    echo "export const pages = new Map<string, string>(["
    for page in privacy support terms; do
        printf '  ["%s", ' "$page"
        jq -Rs . < "$ROOT/docs/$page.txt"
        echo "  ],"
    done
    echo "]);"
} > "$OUTPUT"
